### ISSUE TITLE
Sometimes it finishes. Sometimes not.

### ISSUE THREAD

**Issue by noobtoob4lyfe** [facebookresearch/consistent_depth#12]
I was able to get one video to go all the way through the pipe and output successful video results.  Since then I get this error on every other video I try.  All my clips are shot with the same camera and are roughly 4 seconds long.  Any advice would be appreciated.

"Elapsed time: 16.860 [minutes]
2020-08-26 19:16:37,511 - INFO - #models = 0
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    dp.process(params)
  File "/content/consistent_depth/process.py", line 117, in process
    return self.pipeline(params)
  File "/content/consistent_depth/process.py", line 62, in pipeline
    valid_frames = calibrate_scale(self.video, self.out_dir, frame_range, params)
  File "/content/consistent_depth/scale_calibration.py", line 184, in calibrate_scale
    video.path, colmap.sparse_dir(colmap_dir, 0)
  File "/content/consistent_depth/scale_calibration.py", line 74, in make_camera_params_from_colmap
    cameras, images, points3D = load_colmap.read_model(path=sparse_dir, ext=".bin")
  File "/content/consistent_depth/third_party/colmap/scripts/python/read_write_model.py", line 416, in read_model
    cameras = read_cameras_binary(os.path.join(path, "cameras" + ext))
  File "/content/consistent_depth/third_party/colmap/scripts/python/read_write_model.py", line 135, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'results/GH017205/colmap_dense/sparse/0/cameras.bin'
Done. Your results are saved at /content/consistent_depth/.
Video results are at /content/consistent_depth/results/GH017205/R_hierarchical2_mc/videos/.
Disparity maps are at /content/consistent_depth/results/GH017205/R_hierarchical2_mc/B0.1_R1.0_PL1-0_LR0.0004_BS4_Oadam/depth"

**Comment by roxanneluo** [comment]
Hi,

#models=0 means that COLMAP fails to register any model. Typically, COLMAP can fail when the sequence doesn't have enough baseline between views, scenes is too dynamic or lack features. You may also consider pre-calibrate your camera intrinsics to facilitate camera registration.
