### ISSUE TITLE
cannot extract model file from FlowNet2_checkpoint.pth.tar

### ISSUE THREAD

**Issue by KaqiKaqi** [facebookresearch/consistent_depth#27]
Hi, I downloaded the model file from chrome webbrowser directly and I got the FlowNet2_checkpoint.pth.tar file.
Then I tried to extract the flownet2.pth from it as described in ./scripts/download_model.sh, but it turned out I couldn't extract it.
I cannot use gdown to download the model file.

**Comment by Ahadiandian** [comment]
I also ran into the problem. You just need to rename the package flownet2.pth.tar to flownet2.pth. It's already a model file instead of a tar.

**Comment by jankais3r** [comment]
<img width="1091" alt="Colab Error" src="https://user-images.githubusercontent.com/2159464/104770905-a10f7d80-5771-11eb-96d3-c8df5948b3d9.png">

The Colab notebook is likely failing for the same reason.

**Comment by jiqibuxuexi** [comment]
Loading pretrained model from 'checkpoints/flownet2.pth'.
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    dp.process(params)
  File "/home/gsk/consistent_depth-master/process.py", line 117, in process
    return self.pipeline(params)
  File "/home/gsk/consistent_depth-master/process.py", line 71, in pipeline
    self.flow.compute_flow(frame_pairs, params.flow_checkpoint)
  File "/home/gsk/consistent_depth-master/flow.py", line 143, in compute_flow
    optical_flow_flownet2_homography.process(args)
  File "/home/gsk/consistent_depth-master/optical_flow_flownet2_homography.py", line 250, in process
    flownet2_ckpt = torch.load(args.pretrained_model_flownet2)
  File "/usr/lib/python3/dist-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/flownet2.pth'

**Comment by jiqibuxuexi** [comment]
i also met this problem.it is hard for me to solve .damn it .

**Comment by ajinkyapuar** [comment]
> I also ran into the problem. You just need to rename the package flownet2.pth.tar to flownet2.pth. It's already a model file instead of a tar.

Yes, this works.
