### ISSUE TITLE
No module named 'networks'

### ISSUE THREAD

**Issue by fisakhan** [facebookresearch/consistent_depth#55]
By running the 
```
python main.py --video_file data/videos/ayush.mp4 --path results/ayush \
  --camera_params "1671.770118, 540, 960" --camera_model "SIMPLE_PINHOLE" \
  --make_video
```
I get the following error:
Traceback (most recent call last):

> File "/home/Projects/consistent_depth/consistent_depth/third_party/flownet2/models.py", line 12, in
> from networks.resample2d_package.resample2d import Resample2d
> ModuleNotFoundError: No module named 'networks'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "main.py", line 5, in
> from process import DatasetProcessor
> File "/home/Projects/consistent_depth/consistent_depth/process.py", line 10, in
> from flow import Flow
> File "/home/Projects/consistent_depth/consistent_depth/flow.py", line 15, in
> import optical_flow_flownet2_homography
> File "/home/Projects/consistent_depth/consistent_depth/optical_flow_flownet2_homography.py", line 11, in
> from third_party.flownet2.models import FlowNet2
> File "/home/Projects/consistent_depth/consistent_depth/third_party/flownet2/models.py", line 23, in
> from .networks.channelnorm_package.channelnorm import ChannelNorm
> File "/home/Projects/consistent_depth/consistent_depth/third_party/flownet2/networks/channelnorm_package/channelnorm.py", line 5, in
> import channelnorm_cuda
> ModuleNotFoundError: No module named 'channelnorm_cuda'

**Comment by BruceYu-Bit** [comment]
+1   I met the same problem

**Comment by Udinanon** [comment]
I think it's an issue of uncompiled CUDA pakages. The documentation is not fully detailed on this
You need a CUDA developer setup, so both CUDA and NVCC
then after cloning and setting up you need to go to `third_party/flownet2/networks/` and for each of the folders, so `channelnorm_package`, `correlation_package` and `resampl2d_package` enter in the folder and run `python setup.py install` to install and compile the packages.
