### ISSUE TITLE
PatchMatch Problem and flownet errors

### ISSUE THREAD

**Issue by AlverGant** [facebookresearch/consistent_depth#61]
Trying to use on a series of clips, some work and some do not, exihibing errors like this on colmap:

processing view 24 / 24 for frame_000332.png
==============================================================================

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_idx: 0
src_image_idxs: 11

and finally on flownet:

**********************
****  Fine-tuning  ****
***********************
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    dp.process(params)
  File "/home/alvinho/Downloads/video2depth/consistent_depth/process.py", line 117, in process
    return self.pipeline(params)
  File "/home/alvinho/Downloads/video2depth/consistent_depth/process.py", line 88, in pipeline
    ft.fine_tune(writer=self.writer)
  File "/home/alvinho/Downloads/video2depth/consistent_depth/depth_fine_tuning.py", line 257, in fine_tune
    validate(0, 0)
  File "/home/alvinho/Downloads/video2depth/consistent_depth/depth_fine_tuning.py", line 248, in validate
    criterion, val_data_loader, suffix(epoch, niters)
  File "/home/alvinho/Downloads/video2depth/consistent_depth/depth_fine_tuning.py", line 323, in eval_and_save
    for _, data in zip(range(N), data_loader):
  File "/home/alvinho/anaconda3/envs/consistent_depth/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/alvinho/anaconda3/envs/consistent_depth/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/alvinho/anaconda3/envs/consistent_depth/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/alvinho/anaconda3/envs/consistent_depth/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/alvinho/anaconda3/envs/consistent_depth/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/alvinho/anaconda3/envs/consistent_depth/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/alvinho/anaconda3/envs/consistent_depth/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/alvinho/Downloads/video2depth/consistent_depth/loaders/video_dataset.py", line 172, in __getitem__
    intrinsics = torch.stack([self.intrinsics[k] for k in pair], dim=0)
  File "/home/alvinho/Downloads/video2depth/consistent_depth/loaders/video_dataset.py", line 172, in <listcomp>
    intrinsics = torch.stack([self.intrinsics[k] for k in pair], dim=0)
IndexError: index 214 is out of bounds for dimension 0 with size 10

**Comment by rafaelperez** [comment]
@AlverGant Were you able to get past these errors? I'm hitting similar errors, where most of the time the process doesn't finish due to a similar error message: `IndexError: index X is out of bounds for dimension 0 with size Y`

I've tried to update **colmap** to the latest version but still no luck.
